// app.js (GitHub Pages friendly)
// Loads FTSE snapshot from /data/ftse100.json (generated by GitHub Actions),
// injects BGEO.L, ranks by market cap, and renders.

const DATA_URL = './data/ftse100.json';

// Candidate to add (BGEO on LSE is typically BGEO.L)
const BGEO_CANDIDATE = {
  name: 'Bank of Georgia Group',
  ticker: 'BGEO.L',
};

// ---- Helpers ----
function fmtNumber(n) {
  if (n === null || n === undefined || !Number.isFinite(n)) return '—';
  return n.toLocaleString(undefined, { maximumFractionDigits: 2 });
}

function fmtMoney(n) {
  if (n === null || n === undefined || !Number.isFinite(n)) return '—';
  return n.toLocaleString(undefined, { maximumFractionDigits: 0 });
}

function normalizeTicker(t) {
  return (t || '').trim().toUpperCase();
}

function getEl(id) {
  return document.getElementById(id);
}

// Try to find common UI elements; if missing, we still render table.
function setStatus(text) {
  const el =
    getEl('status') ||
    document.querySelector('[data-status]') ||
    document.querySelector('.status') ||
    document.querySelector('#statusText');
  if (el) el.textContent = text;
}

function setCardValue(key, value) {
  // Optional: if your HTML has these IDs, we fill them. If not, ignore.
  const map = {
    total: ['totalCompanies', 'total-companies', 'cardTotal'],
    bgeoRank: ['bgeoRank', 'bgeo-rank', 'cardBgeoRank'],
    bgeoMcap: ['bgeoMarketCap', 'bgeo-market-cap', 'cardBgeoMcap'],
  };
  const ids = map[key] || [];
  for (const id of ids) {
    const el = getEl(id);
    if (el) {
      el.textContent = value;
      return;
    }
  }
}

function findTableBody() {
  // Prefer an existing table body if your HTML has one
  return (
    document.querySelector('table tbody') ||
    document.querySelector('#table tbody') ||
    document.querySelector('#constituents tbody')
  );
}

function ensureTable() {
  // If the page already has a table, use it; otherwise create a simple one.
  let table = document.querySelector('table');
  if (!table) {
    table = document.createElement('table');
    table.style.width = '100%';
    table.style.borderCollapse = 'collapse';
    table.innerHTML = `
      <thead>
        <tr>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Rank</th>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Company</th>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Ticker</th>
          <th style="text-align:right;padding:8px;border-bottom:1px solid #333;">Price</th>
          <th style="text-align:right;padding:8px;border-bottom:1px solid #333;">Market Cap</th>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Notes</th>
        </tr>
      </thead>
      <tbody></tbody>
    `;
    document.body.appendChild(table);
  }
  let tbody = table.querySelector('tbody');
  if (!tbody) {
    tbody = document.createElement('tbody');
    table.appendChild(tbody);
  }
  return tbody;
}

async function loadSnapshot() {
  const res = await fetch(DATA_URL, { cache: 'no-store' });
  if (!res.ok) throw new Error(`Failed to load ${DATA_URL} (${res.status})`);
  return res.json();
}

function injectBGEO(companies) {
  const tickers = new Set(companies.map((c) => normalizeTicker(c.ticker)));
  if (!tickers.has(normalizeTicker(BGEO_CANDIDATE.ticker))) {
    companies.push({
      ...BGEO_CANDIDATE,
      price: nu
