// app.js (GitHub Pages friendly)
// Loads FTSE snapshot from /data/ftse100.json (generated by GitHub Actions),
// injects BGEO.L, ranks by market cap, and renders.

const DATA_URL = './data/ftse100.json';

// Candidate to add (BGEO on LSE is typically BGEO.L)
const BGEO_CANDIDATE = {
  name: 'Bank of Georgia Group',
  ticker: 'BGEO.L',
};

// ---- Helpers ----
function fmtNumber(n) {
  if (n === null || n === undefined || !Number.isFinite(n)) return '—';
  return n.toLocaleString(undefined, { maximumFractionDigits: 2 });
}

function fmtMoney(n) {
  if (n === null || n === undefined || !Number.isFinite(n)) return '—';
  return n.toLocaleString(undefined, { maximumFractionDigits: 0 });
}

function normalizeTicker(t) {
  return (t || '').trim().toUpperCase();
}

function getEl(id) {
  return document.getElementById(id);
}

// Try to find common UI elements; if missing, we still render table.
function setStatus(text) {
  const el =
    getEl('status') ||
    document.querySelector('[data-status]') ||
    document.querySelector('.status') ||
    document.querySelector('#statusText');
  if (el) el.textContent = text;
}

function setCardValue(key, value) {
  // Optional: if your HTML has these IDs, we fill them. If not, ignore.
  const map = {
    total: ['totalCompanies', 'total-companies', 'cardTotal'],
    bgeoRank: ['bgeoRank', 'bgeo-rank', 'cardBgeoRank'],
    bgeoMcap: ['bgeoMarketCap', 'bgeo-market-cap', 'cardBgeoMcap'],
  };
  const ids = map[key] || [];
  for (const id of ids) {
    const el = getEl(id);
    if (el) {
      el.textContent = value;
      return;
    }
  }
}

function findTableBody() {
  // Prefer an existing table body if your HTML has one
  return (
    document.querySelector('table tbody') ||
    document.querySelector('#table tbody') ||
    document.querySelector('#constituents tbody')
  );
}

function ensureTable() {
  // If the page already has a table, use it; otherwise create a simple one.
  let table = document.querySelector('table');
  if (!table) {
    table = document.createElement('table');
    table.style.width = '100%';
    table.style.borderCollapse = 'collapse';
    table.innerHTML = `
      <thead>
        <tr>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Rank</th>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Company</th>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Ticker</th>
          <th style="text-align:right;padding:8px;border-bottom:1px solid #333;">Price</th>
          <th style="text-align:right;padding:8px;border-bottom:1px solid #333;">Market Cap</th>
          <th style="text-align:left;padding:8px;border-bottom:1px solid #333;">Notes</th>
        </tr>
      </thead>
      <tbody></tbody>
    `;
    document.body.appendChild(table);
  }
  let tbody = table.querySelector('tbody');
  if (!tbody) {
    tbody = document.createElement('tbody');
    table.appendChild(tbody);
  }
  return tbody;
}

async function loadSnapshot() {
  const res = await fetch(DATA_URL, { cache: 'no-store' });
  if (!res.ok) throw new Error(`Failed to load ${DATA_URL} (${res.status})`);
  return res.json();
}

function injectBGEO(companies) {
  const tickers = new Set(companies.map((c) => normalizeTicker(c.ticker)));
  if (!tickers.has(normalizeTicker(BGEO_CANDIDATE.ticker))) {
    companies.push({
      ...BGEO_CANDIDATE,
      price: null,
      marketCap: null,
      updatedAt: new Date().toISOString(),
      addedCandidate: true,
    });
  }
  return companies;
}

function sortByMarketCap(companies) {
  // Put known market caps first, highest to lowest; nulls go to bottom.
  return [...companies].sort((a, b) => {
    const am = Number.isFinite(a.marketCap) ? a.marketCap : -Infinity;
    const bm = Number.isFinite(b.marketCap) ? b.marketCap : -Infinity;
    return bm - am;
  });
}

function renderTable(companies) {
  const tbody = findTableBody() || ensureTable();
  tbody.innerHTML = '';

  companies.forEach((c, idx) => {
    const tr = document.createElement('tr');
    const rank = idx + 1;
    const notes = c.addedCandidate ? 'Added candidate' : '';

    tr.innerHTML = `
      <td style="padding:8px;border-bottom:1px solid #222;">${rank}</td>
      <td style="padding:8px;border-bottom:1px solid #222;">${c.name || '—'}</td>
      <td style="padding:8px;border-bottom:1px solid #222;">${c.ticker || '—'}</td>
      <td style="padding:8px;border-bottom:1px solid #222;text-align:right;">${fmtNumber(c.price)}</td>
      <td style="padding:8px;border-bottom:1px solid #222;text-align:right;">${fmtMoney(c.marketCap)}</td>
      <td style="padding:8px;border-bottom:1px solid #222;">${notes}</td>
    `;
    tbody.appendChild(tr);
  });
}

function computeBGEO(companiesSorted) {
  const idx = companiesSorted.findIndex(
    (c) => normalizeTicker(c.ticker) === normalizeTicker(BGEO_CANDIDATE.ticker),
  );
  if (idx === -1) return null;
  const c = companiesSorted[idx];
  return { rank: idx + 1, marketCap: c.marketCap };
}

async function main() {
  try {
    setStatus('Loading FTSE snapshot…');

    const snapshot = await loadSnapshot();
    const updatedAt = snapshot.updatedAt || snapshot.companies?.[0]?.updatedAt || null;

    let companies = Array.isArray(snapshot.companies) ? snapshot.companies : [];
    companies = injectBGEO(companies);
    const sorted = sortByMarketCap(companies);

    renderTable(sorted);

    setCardValue('total', String(sorted.length));

    const bgeo = computeBGEO(sorted);
    if (bgeo) {
      setCardValue('bgeoRank', String(bgeo.rank));
      setCardValue('bgeoMcap', fmtMoney(bgeo.marketCap));
    }

    setStatus(
      updatedAt
        ? `Loaded from data/ftse100.json (updated ${updatedAt})`
        : 'Loaded from data/ftse100.json',
    );

    // If your page has a button with text "Refresh quotes", we can reload on click.
    const refreshBtn =
      document.querySelector('button#refresh') ||
      Array.from(document.querySelectorAll('button')).find((b) =>
        (b.textContent || '').toLowerCase().includes('refresh'),
      );
    if (refreshBtn) {
      refreshBtn.addEventListener('click', () => window.location.reload());
    }
  } catch (err) {
    console.error(err);
    setStatus(`Failed to load snapshot. Using fallback message. (${err.message})`);
  }
}

main();
